#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative 'user_service_types'

module UserService
  module UserService
    class Client
      include ::Thrift::Client

      def createUser(name, age)
        send_createUser(name, age)
        return recv_createUser()
      end

      def send_createUser(name, age)
        send_message('createUser', CreateUser_args, :name => name, :age => age)
      end

      def recv_createUser()
        fname, mtype, rseqid = receive_message_begin()
        handle_exception(mtype)
        if reply_seqid(rseqid)==false
          raise "seqid reply faild"
        end
        result = receive_message(CreateUser_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'createUser failed: unknown result')
      end

      def getUser(userId)
        send_getUser(userId)
        return recv_getUser()
      end

      def send_getUser(userId)
        send_message('getUser', GetUser_args, :userId => userId)
      end

      def recv_getUser()
        fname, mtype, rseqid = receive_message_begin()
        handle_exception(mtype)
        if reply_seqid(rseqid)==false
          raise "seqid reply faild"
        end
        result = receive_message(GetUser_result)
        return result.success unless result.success.nil?
        raise result.ex unless result.ex.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'getUser failed: unknown result')
      end

      def updateUser(user)
        send_updateUser(user)
        return recv_updateUser()
      end

      def send_updateUser(user)
        send_message('updateUser', UpdateUser_args, :user => user)
      end

      def recv_updateUser()
        fname, mtype, rseqid = receive_message_begin()
        handle_exception(mtype)
        if reply_seqid(rseqid)==false
          raise "seqid reply faild"
        end
        result = receive_message(UpdateUser_result)
        return result.success unless result.success.nil?
        raise result.ex unless result.ex.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'updateUser failed: unknown result')
      end

      def deleteUser(userId)
        send_deleteUser(userId)
        recv_deleteUser()
      end

      def send_deleteUser(userId)
        send_message('deleteUser', DeleteUser_args, :userId => userId)
      end

      def recv_deleteUser()
        fname, mtype, rseqid = receive_message_begin()
        handle_exception(mtype)
        if reply_seqid(rseqid)==false
          raise "seqid reply faild"
        end
        result = receive_message(DeleteUser_result)
        raise result.ex unless result.ex.nil?
        return
      end

      def getAllUsers()
        send_getAllUsers()
        return recv_getAllUsers()
      end

      def send_getAllUsers()
        send_message('getAllUsers', GetAllUsers_args)
      end

      def recv_getAllUsers()
        fname, mtype, rseqid = receive_message_begin()
        handle_exception(mtype)
        if reply_seqid(rseqid)==false
          raise "seqid reply faild"
        end
        result = receive_message(GetAllUsers_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'getAllUsers failed: unknown result')
      end

      def validateUserData(name, age, isActive)
        send_validateUserData(name, age, isActive)
        return recv_validateUserData()
      end

      def send_validateUserData(name, age, isActive)
        send_message('validateUserData', ValidateUserData_args, :name => name, :age => age, :isActive => isActive)
      end

      def recv_validateUserData()
        fname, mtype, rseqid = receive_message_begin()
        handle_exception(mtype)
        if reply_seqid(rseqid)==false
          raise "seqid reply faild"
        end
        result = receive_message(ValidateUserData_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'validateUserData failed: unknown result')
      end

      def logUserActivity(action, userId, timestamp)
        send_logUserActivity(action, userId, timestamp)
      end

      def send_logUserActivity(action, userId, timestamp)
        send_oneway_message('logUserActivity', LogUserActivity_args, :action => action, :userId => userId, :timestamp => timestamp)
      end
    end

    class Processor
      include ::Thrift::Processor

      def process_createUser(seqid, iprot, oprot)
        args = read_args(iprot, CreateUser_args)
        result = CreateUser_result.new()
        result.success = @handler.createUser(args.name, args.age)
        write_result(result, oprot, 'createUser', seqid)
      end

      def process_getUser(seqid, iprot, oprot)
        args = read_args(iprot, GetUser_args)
        result = GetUser_result.new()
        begin
          result.success = @handler.getUser(args.userId)
        rescue ::UserService::UserNotFoundException => ex
          result.ex = ex
        end
        write_result(result, oprot, 'getUser', seqid)
      end

      def process_updateUser(seqid, iprot, oprot)
        args = read_args(iprot, UpdateUser_args)
        result = UpdateUser_result.new()
        begin
          result.success = @handler.updateUser(args.user)
        rescue ::UserService::UserNotFoundException => ex
          result.ex = ex
        end
        write_result(result, oprot, 'updateUser', seqid)
      end

      def process_deleteUser(seqid, iprot, oprot)
        args = read_args(iprot, DeleteUser_args)
        result = DeleteUser_result.new()
        begin
          @handler.deleteUser(args.userId)
        rescue ::UserService::UserNotFoundException => ex
          result.ex = ex
        end
        write_result(result, oprot, 'deleteUser', seqid)
      end

      def process_getAllUsers(seqid, iprot, oprot)
        args = read_args(iprot, GetAllUsers_args)
        result = GetAllUsers_result.new()
        result.success = @handler.getAllUsers()
        write_result(result, oprot, 'getAllUsers', seqid)
      end

      def process_validateUserData(seqid, iprot, oprot)
        args = read_args(iprot, ValidateUserData_args)
        result = ValidateUserData_result.new()
        result.success = @handler.validateUserData(args.name, args.age, args.isActive)
        write_result(result, oprot, 'validateUserData', seqid)
      end

      def process_logUserActivity(seqid, iprot, oprot)
        args = read_args(iprot, LogUserActivity_args)
        @handler.logUserActivity(args.action, args.userId, args.timestamp)
        return
      end

    end

    # HELPER FUNCTIONS AND STRUCTURES

    class CreateUser_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      NAME = 1
      AGE = 2

      FIELDS = {
        NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
        AGE => {:type => ::Thrift::Types::I32, :name => 'age'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CreateUser_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::UserService::User}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class GetUser_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      USERID = 1

      FIELDS = {
        USERID => {:type => ::Thrift::Types::I64, :name => 'userId'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class GetUser_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0
      EX = 1

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::UserService::User},
        EX => {:type => ::Thrift::Types::STRUCT, :name => 'ex', :class => ::UserService::UserNotFoundException}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class UpdateUser_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      USER = 1

      FIELDS = {
        USER => {:type => ::Thrift::Types::STRUCT, :name => 'user', :class => ::UserService::User}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class UpdateUser_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0
      EX = 1

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::UserService::User},
        EX => {:type => ::Thrift::Types::STRUCT, :name => 'ex', :class => ::UserService::UserNotFoundException}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class DeleteUser_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      USERID = 1

      FIELDS = {
        USERID => {:type => ::Thrift::Types::I64, :name => 'userId'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class DeleteUser_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      EX = 1

      FIELDS = {
        EX => {:type => ::Thrift::Types::STRUCT, :name => 'ex', :class => ::UserService::UserNotFoundException}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class GetAllUsers_args
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class GetAllUsers_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::UserService::User}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class ValidateUserData_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      NAME = 1
      AGE = 2
      ISACTIVE = 3

      FIELDS = {
        NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
        AGE => {:type => ::Thrift::Types::I32, :name => 'age'},
        ISACTIVE => {:type => ::Thrift::Types::BOOL, :name => 'isActive'}
      }

      def struct_fields; FIELDS; end

      def validate
        raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field name is unset!') unless @name
        raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field age is unset!') unless @age
        raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field isActive is unset!') if @isActive.nil?
      end

      ::Thrift::Struct.generate_accessors self
    end

    class ValidateUserData_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class LogUserActivity_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ACTION = 1
      USERID = 2
      TIMESTAMP = 3

      FIELDS = {
        ACTION => {:type => ::Thrift::Types::STRING, :name => 'action'},
        USERID => {:type => ::Thrift::Types::I64, :name => 'userId'},
        TIMESTAMP => {:type => ::Thrift::Types::STRING, :name => 'timestamp'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class LogUserActivity_result
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end

end
