#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module UserService
  class User; end

  class UserNotFoundException < ::Thrift::Exception; end

  class User
    include ::Thrift::Struct, ::Thrift::Struct_Union
    ID = 1
    NAME = 2
    AGE = 3

    FIELDS = {
      ID => {:type => ::Thrift::Types::I64, :name => 'id'},
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
      AGE => {:type => ::Thrift::Types::I32, :name => 'age'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class UserNotFoundException < ::Thrift::Exception
    include ::Thrift::Struct, ::Thrift::Struct_Union
    def initialize(message=nil)
      super()
      self.message = message
    end

    MESSAGE = 1

    FIELDS = {
      MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
